### ISSUE TITLE
Issue Installing `@elizaos/plugin-evm` After ElizaOS Update

### ISSUE THREAD

**Issue by luisvid** [elizaos-plugins/plugin-evm#3]
Hi,  

After the recent ElizaOS update that moved plugins out of the main repository, I attempted to install the `plugin-evm`, but I consistently encounter the following error:  

### **System Information:**  
- **Node.js version:** v23.3.0  
- **pnpm version:** v9.15.0  

### **Command Executed:**  
```sh
npx elizaos plugins add @elizaos-plugins/plugin-evm
```

### **Error Output:**  
```sh
npx elizaos plugins add @elizaos-plugins/plugin-evm
(node:58090) ExperimentalWarning: CommonJS module /home/luisvid/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /home/luisvid/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Modules in require() is an experimental feature and might change at any time.
(Use `node --trace-warnings ...` to see where the warning was created)

Using Git version 2.43.0  
Cloning `plugin-evm` to `/home/luisvid/dev/agents/eliza/packages/plugin-evm`  
Ensuring the plugin has access to `@elizaos/core`  

**Error Trace:**  

node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: pnpm add @elizaos/core@workspace:* --filter ./packages/plugin-evm
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:882:11)
    at execSync (node:child_process:954:15)
    at Command.<anonymous> (/home/luisvid/dev/agents/eliza/packages/cli/index.js:107:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  status: 1,
  signal: null,
 output: [
    null,
    Buffer(390) [Uint8Array] [
       47, 104, 111, 109, 101,  47, 108, 117, 105, 115, 118, 105,
      100,  47, 100, 101, 118,  47,  97, 103, 101, 110, 116, 115,
       47, 101, 108, 105, 122,  97,  47, 112,  97,  99, 107,  97,
      103, 101, 115,  47, 112, 108, 117, 103, 105, 110,  45, 101,
      118, 109,  58,  10, 226, 128, 137,  69,  82,  82,  95,  80,
       78,  80,  77,  95,  87,  79,  82,  75,  83,  80,  65,  67,
       69,  95,  80,  75,  71,  95,  78,  79,  84,  95,  70,  79,
       85,  78,  68, 226, 128, 137,  32,  73, 110,  32, 112,  97,
       99, 107,  97, 103,
      ... 290 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 58148,
  stdout: Buffer(390) [Uint8Array] [
     47, 104, 111, 109, 101,  47, 108, 117, 105, 115, 118, 105,
    100,  47, 100, 101, 118,  47,  97, 103, 101, 110, 116, 115,
     47, 101, 108, 105, 122,  97,  47, 112,  97,  99, 107,  97,
    103, 101, 115,  47, 112, 108, 117, 103, 105, 110,  45, 101,
    118, 109,  58,  10, 226, 128, 137,  69,  82,  82,  95,  80,
     78,  80,  77,  95,  87,  79,  82,  75,  83,  80,  65,  67,
     69,  95,  80,  75,  71,  95,  78,  79,  84,  95,  70,  79,
     85,  78,  68, 226, 128, 137,  32,  73, 110,  32, 112,  97,
     99, 107,  97, 103,
    ... 290 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}
```

### **Additional Notes:**  
- The issue seems to stem from `pnpm` failing to install `@elizaos/core` within the `plugin-evm` package.  
- There is also an experimental warning related to loading ES Modules with `require()`.  
- The Git cloning step completes successfully, but the dependency installation fails.  

Any guidance on resolving this issue would be greatly appreciated.  

Best regards,  
Luis

**Comment by Oxwagmi** [comment]
to fix the issue first run ```npx elizaos plugins add @elizaos-plugins/plugin-tee``` then  go to local folder   `eliza/packages/plugin-evm`   open package.json  file , similar to  https://github.com/elizaos-plugins/plugin-evm/blob/main/package.json#L22   replace         ```"@elizaos/plugin-tee": "workspace:*"```  with       ``` "@elizaos-plugins/plugin-tee": "workspace:*",```

**Comment by Oxwagmi** [comment]
> > to fix the issue first run `npx elizaos plugins add @elizaos-plugins/plugin-tee` then go to local folder `eliza/packages/plugin-evm` open package.json file , similar to https://github.com/elizaos-plugins/plugin-evm/blob/main/package.json#L22 replace `"@elizaos/plugin-tee": "workspace:*"` with ` "@elizaos-plugins/plugin-tee": "workspace:*",`
> 
> Also need 2 more things:
> 
>     1. navigate to the `packages/plugin-evm` and install `node-cache` package using `pnpm install node-cache` command.
> 
>     2. navigate to the `packages/plugin-tee` and install `undici` package using `pnpm install undici` command.


> Thanks, 0xsaymon! I also needed to follow those two steps to get it working!

yes you are correct, I used    
``` 
node command then 
import("@elizaos-plugins/plugin-evm").then(console.log).catch(console.error);
 ```
  to figure out the missing packages

**Comment by avdheshcharjan** [comment]
it is fixed now. no need of this solution

**Comment by omariosman** [comment]
Thanks @Oxwagmi @0xsaymon 
But I am still having this error: `Failed to import plugin: @elizaos-plugins/plugin-evm Error: Cannot find package '@elizaos/plugin-tee' imported from /home/omarosman23/Documents/learn/ai-agents/eliza/packages/plugin-evm/dist/index.js`

When I try to import plugin-tee itself I encounter this error:
`Failed to import plugin: @elizaos-plugins/plugin-tee TypeError: basex is not a function`

**Comment by omariosman** [comment]
which version for plugin-evm should I currently use @avdheshcharjan

**Comment by avdheshcharjan** [comment]
for import plugins, there are few plugins that use other plugins. so you need to be careful. 

for plugin-evm, try the latest one: https://github.com/elizaos-plugins/plugin-evm/releases/tag/v1.0.0-beta.53

**Comment by omariosman** [comment]
@wtfsayo Is there a plugin called evm? 
When I use `npx elizaos plugins list | grep evm` I cannot find except `@elizaos-plugins/plugin-evm`

**Comment by wtfsayo** [comment]
> [@wtfsayo](https://github.com/wtfsayo) Is there a plugin called evm? When I use `npx elizaos plugins list | grep evm` I cannot find except `@elizaos-plugins/plugin-evm`
> 
> When I use `npx elizaos plugins add evm`, it gives me this message: `Plugin evm not found`

recommend global installation and trying without npx
